Document: phpquery
Title: Debian phpquery Manual
Author: <insert document author here>
Abstract: This manual describes what phpquery is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/phpquery/phpquery.sgml.gz

Format: postscript
Files: /usr/share/doc/phpquery/phpquery.ps.gz

Format: text
Files: /usr/share/doc/phpquery/phpquery.text.gz

Format: HTML
Index: /usr/share/doc/phpquery/html/index.html
Files: /usr/share/doc/phpquery/html/*.html
